export const ADD_INGREDIENT = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_COST = 'SET_INGREDIENTS_COST';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';
export const FETCH_INGREDIENTS_COST_FAIL = 'FETCH_INGREDIENTS_COST_FAIL';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';